outline_task:
  description: >
    Erstelle eine Gliederung für eine Seminararbeit mit dem Titel : " {seminararbeitthema} "
    
    Die Seminararbeit hat einen Umfang von 12 - 15 Seiten an Text.

    Bei der Gliederung muss erkennbar sein, welches Kapitel zu Einleitung, Hauptteil und Schluss zugehörig ist. 
    Diese Information kann in Klammern hinter die jeweiligen Kapitel hinzugefügt werden.

    Gliederungspunkte dürfen maximal zwei Ebenen der Nummerierung aufweisen. Strukturen wie '2.3.1' sind unzulässig
  expected_output: >
    Eine Gliederung für eine Seminararbeit mit dem Titel "{seminararbeitthema}".
    Gliederungspunkte dürfen maximal zwei Ebenen der Nummerierung aufweisen. Strukturen wie '2.3.1' sind unzulässig
  agent: outline_creator
  output_file: '{path}.md'